################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false

################################################################
# Access Logging
################################################################
# enable Access logs
accessLog: {}
#Configuring Multiple Filters
# accessLog:
#   filters:    
#     statusCodes:
#       - "404"
#     retryAttempts: true
#     minDuration: "10ms"

################################################################
# Traefik Logging -  DEBUG, PANIC, FATAL, ERROR, WARN, and INFO (DEFAULT is ERROR)
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

################################################################
# Challenege DNS
################################################################
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: your_email@example.com 
#       storage: acme.json
#       dnsChallenge:
#         provider: digitalocean
#         delayBeforeCheck: 0
