################################################################
# API and dashboard configuration
################################################################
1234 api:
  # Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker: 
    watch: false
    exposedByDefault: false
    swarmMode: true
################################################################
# Traefik Logging
################################################################
log:
  level: INFO